<?php 
defined( 'ABSPATH' ) or die( 'No script kiddies please!' ); 

//Define a psta de upload
function efw_basedir($dirs){   
   $dirs['subdir'] = 'import_excel';
   $dirs['path'] = $dirs['basedir'] .'/import_excel';
   $dirs['url'] = $dirs['baseurl'].'/import_excel';
    
   return $dirs;
}

add_filter( 'upload_dir', 'efw_basedir' );

//Faz o upload do arquivo
if ( ! function_exists( 'wp_handle_upload' ) ) {
   require_once( ABSPATH . 'wp-admin/includes/file.php' );
}

$uploadedfile = $_FILES['file'];

$upload_overrides = array(
   'test_form' => true
);

$movefile = wp_handle_upload( $uploadedfile, $upload_overrides );

if ( $movefile && ! isset( $movefile['error'] ) ) {
   echo __( 'File is valid, and was successfully uploaded.', 'textdomain' ) . "\n";
   var_dump( $movefile );
} else {
   /*
    * Error generated by _wp_handle_upload()
    * @see _wp_handle_upload() in wp-admin/includes/file.php
    */
   echo $movefile['error'];
}

?>

<div class="wrap">
<h1>Importe os dados aqui</h1>
<h2>Confira os dados e depois clique em importar</h2>
   <form action="#" method="POST" enctype="multipart/form-data">
      <input type="file" name="file">
      <input type="submit" value="Enviar">
   </form>
</div>

<?php

require_once plugin_dir_path( __FILE__ ) . '../vendor/autoload.php';

use PhpOffice\PhpSpredsheet\Reader\Xlsx;
//Processa o upload
if (isset($_POST["import"])) {

   $allowedFileType = [
       'application/vnd.ms-excel',
       'text/xls',
       'text/xlsx',
       'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
   ];

   if(in_array($_FILES['file']['type'],$allowedFileType)){
      $targetPath  = 'uploads/'.$_FILES['file']['name'];
      move_uploaded_file($_FILES['file']['temp_name'],$targetPath);

      $Reader = new PhpOficce\PhpSpreadsheet\reader\Xlsx();
      $spreadsheet = $Reader->load($targetPath);
      $excelSheet = $spreadsheet->getAtiveSheet();
      $spreadSheetAry = $excelSheet->toArray();
      $sheetCount = count($spreadSheetAry);

      vardump($sheetCount);
   }
}
?>