<?php 
defined( 'ABSPATH' ) or die( 'No script kiddies please!' ); 

//Define a pasta de upload
function efw_basedir($dirs){   
   $dirs['subdir'] = 'import_excel';
   $dirs['path'] = $dirs['basedir'] .'/import_excel';
   $dirs['url'] = $dirs['baseurl'].'/import_excel';
    
   return $dirs;
}

add_filter( 'upload_dir', 'efw_basedir' );

//Faz o upload do arquivo
if ( ! function_exists( 'wp_handle_upload' ) ) {
   require_once( ABSPATH . 'wp-admin/includes/file.php' );
}

$uploadedfile = $_FILES['file'];

$upload_overrides = array(
   'test_form' => true
);

$movefile = wp_handle_upload( $uploadedfile, $upload_overrides );

if ( $movefile && ! isset( $movefile['error'] ) ) {
   echo __( 'File is valid, and was successfully uploaded.', 'textdomain' ) . "\n";
   var_dump( $movefile );
} else {
   /*
    * Error generated by _wp_handle_upload()
    * @see _wp_handle_upload() in wp-admin/includes/file.php
    */
   echo $movefile['error'];
}


?>
   <div class="wrap">
   <h1>Importe os dados aqui</h1>
   <h2>Confira os dados e depois clique em importar</h2>
      <form action="#" method="POST" enctype="multipart/form-data">
         <input type="file" name="file">
         <input type="submit" value="Enviar">
      </form>
   </div>
<style>
@import url('https://fonts.googleapis.com/css2?family=Roboto&display=swap');
   body{
       font-size: 32px;
   }
    h1{
        font-family: Roboto;
        
    }
</style>
<php




